### ISSUE TITLE
Not able to convert

### ISSUE THREAD

**Issue by Wikunia** [paaguti/svg2tikz#1]
Hi,

I have a problem to convert this svg into tikz. It was generated the other way around (tikz -> svg)
http://blog.wikunia.de/user/pages/blog/2015-05-18-first-steps/xor.svg

My error messages:

```
python2 svg2tikz.py -a xor.svg 
 xor.svg --> xor.tex 
WARNING: <use ../> not processed
WARNING: <use ../> not processed
WARNING: <use ../> not processed
WARNING: <use ../> not processed
Traceback (most recent call last):
  File "svg2tikz.py", line 613, in <module>
    main()
  File "svg2tikz.py", line 608, in main
    processor.mkTikz(root)
  File "svg2tikz.py", line 560, in mkTikz
    self.process_g(elem)
  File "svg2tikz.py", line 540, in process_g
    xlate[x](child)
  File "svg2tikz.py", line 530, in <lambda>
    'path':    lambda e: self.process_path(e)
  File "svg2tikz.py", line 362, in process_path
    pid = elem.attrib['id']
  File "lxml.etree.pyx", line 2366, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:62258)
KeyError: 'id'
```

**Comment by paaguti** [comment]
Hi Ole, danke für die Fehlermeldung. Ich nehme sie mir bei der ersten
Gelegenheit vor...
